-- ============================================================================
--  monitors.lua  (translated from monitors.conf)
-- ----------------------------------------------------------------------------
--  Original conf line format was:
--     monitor = NAME, RESOLUTION@HZ, POSITION, SCALE, [extra args...]
--  In Lua each monitor is one hl.monitor{} call with named fields.
--  Generated by nwg-displays — it will keep editing monitors.conf, not this.
-- ============================================================================

-- monitor=DP-1,2560x1440@240.0,1920x0,1.0,vrr,0
hl.monitor({
    output   = "DP-1",
    mode     = "2560x1440@240.0",
    position = "1920x0",
    scale    = 1.0,
    vrr      = 0,
})

-- monitor=HDMI-A-1,1920x1080@60.0,0x0,1.0
hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1920x1080@60.0",
    position = "0x0",
    scale    = 1.0,
})
