-- Generated by nwg-displays on 2026-08-02 at 17:05:14. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "3840x2560@119.99",
    position = "2560x0",
    scale = 1.6,
    bitdepth = 10
})
hl.monitor({
    output = "DP-2",
    mode = "2560x1440@240.0",
    position = "0x0",
    scale = 1.0
})
