-- ============================================================================
--  hyprland/colors.lua  (translated from hyprland/colors.conf)
-- ----------------------------------------------------------------------------
--  This file runs AFTER general.lua, so its hl.config{} values override the
--  border colors set there (same as the old source order).
--  (Normally this file is regenerated by illogical-impulse's theming.)
-- ============================================================================

hl.config({
    general = {
        col = {
            active_border   = "rgba(8b919877)",
            inactive_border = "rgba(41484d55)",
        },
    },
    misc = {
        background_color = "rgba(101417FF)",
    },
})

-- Border color for pinned windows
hl.window_rule({
    match = { pin = true },
    border_color = "rgba(93cdf6AA) rgba(93cdf677)",
})

-- ----------------------------------------------------------------------------
-- hyprbars PLUGIN config (was active in colors.conf).
-- hyprbars is a third-party plugin; configuring plugins from Lua is not yet
-- something the official example demonstrates, so this is left COMMENTED to
-- avoid load errors. If you use hyprbars, verify the shape against the plugin
-- docs and the Lua plugin API, then uncomment.
-- ----------------------------------------------------------------------------
-- hl.config({
--     plugin = {
--         hyprbars = {
--             bar_text_font = "Google Sans Flex Medium, Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif",
--             bar_height = 30,
--             bar_padding = 10,
--             bar_button_padding = 5,
--             bar_precedence_over_border = true,
--             bar_part_of_window = true,
--             bar_color = "rgba(101417FF)",
--             col = { text = "rgba(dfe3e7FF)" },
--         },
--     },
-- })
-- The `hyprbars-button = color, size, glyph, on-click` lines have no obvious
-- Lua table equivalent yet — keep them in a .conf if you need them, or check
-- the plugin's updated docs.
